%{?!ros_distro:%global ros_distro rolling}
%global pkg_name mrt_cmake_modules
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-rolling-mrt-cmake-modules
Version:        1.0.9
Release:        4%{?dist}
Summary:        ROS %{pkg_name} package

License:        BSD
URL:            http://wiki.ros.org/mrt_cmake_modules
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

BuildRequires:  bloom-rpm-macros
BuildRequires:  cmake

%{?bloom_package}

%description
CMake Functions and Modules for automating CMake


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
CMake Functions and Modules for automating CMake


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
CMake Functions and Modules for automating CMake


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%cmake \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="%{bloom_prefix}" \
    -DCMAKE_PREFIX_PATH="%{bloom_prefix}" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
    -DCATKIN_ENABLE_TESTING=OFF \
%endif

%cmake3_build


%install
%cmake_install


%files devel
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Fri Mar 22 2024 Kevin Rösch <kevin.roesch@kit.edu> - 1.0.9-4
- Autogenerated by Bloom
